server: "hub.lambdatest.com"
user: "<YOUR LAMBDATEST USERNAME>"
key: "<YOUR LAMBDATEST KEY>"

common_caps:
  "build": "capybara-lambdatest"
  "name": "single-Test"

browser_caps:
  -
    "browserName": "chrome"
    "version": "latest"
    "platform": "Windows 11"
